---
title: "Getting and Cleaning Data Quiz 3"
author: "KellyPisane"
date: "April 24, 2017"
output: html_document
---

Question 1: 
Create a logical vector that identifies the households on greater 
than 10 acres who sold more than $10,000 worth of agriculture products. 
Assign that logical vector to the variable agricultureLogical. 
Apply the which() function like this to identify the rows of the data 
frame where the logical vector is TRUE.

which(agricultureLogical)

What are the first 3 values that result?

Question 2: 
Using the jpeg package read in the following picture of your instructor into R

https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg

Use the parameter native=TRUE. What are the 30th and 80th quantiles of the resulting data? (some Linux systems may produce an answer 638 different for the 30th quantile)

Question 3: 
Match the data based on the country shortcode. How many of the IDs match? Sort the data frame in descending order by GDP rank (so United States is last). What is the 13th country in the resulting data frame?

Question 4:
What is the average GDP ranking for the "High income: OECD" and "High income: nonOECD" group?

Question 5: 
Cut the GDP ranking into 5 separate quantile groups. Make a table versus Income.Group. How many countries

are Lower middle income but among the 38 nations with highest GDP?